const evidenceSteps={
  source:{title:"Begin with permission and provenance.",body:"A record enters only through an approved source perimeter. Access method, rights class, retrieval date, permitted use, restrictions, and retention are captured before analytical use.",meta:[["Authority","Source approval"],["Output","Permission-linked record"],["Failure condition","Rights or access cannot be established"],["Evidence status","Not yet interpreted"]]},
  fact:{title:"State only what the record establishes.",body:"The factual record is normalized, linked to the precise source, dated, and checked for entity identity. Model-assisted extraction may propose fields; a human validates consequential records.",meta:[["Authority","Record validation"],["Output","Verified or corroborated fact"],["Failure condition","Identity, date, or claim remains ambiguous"],["Evidence status","Verified / corroborated"]]},
  signal:{title:"Name the change without overstating its meaning.",body:"A signal describes an observable event—a trial milestone, financing, leadership change, regulatory movement, or commercialization preparation. It is not itself proof of service need.",meta:[["Authority","Analytical approval"],["Output","Normalized signal"],["Failure condition","No defined ontology match"],["Evidence status","Fact-linked classification"]]},
  hypothesis:{title:"Make the inference visible and defeasible.",body:"The method explains why a signal may imply timing, complexity, or a need worth examining. Contradictory evidence, missing data, and alternative explanations remain alongside the hypothesis.",meta:[["Authority","Account review"],["Output","Inflection and service-relevance hypothesis"],["Failure condition","Inference is presented as fact"],["Evidence status","Inference / early signal"]]},
  decision:{title:"Humans decide what happens next.",body:"A reviewer advances, monitors, defers, excludes, redirects, or marks insufficient evidence. The score informs review; it never owns the disposition.",meta:[["Authority","Distribution approval"],["Output","Portfolio disposition"],["Failure condition","Automated pursuit decision"],["Evidence status","Human-reviewed conclusion"]]}
};
const weights=[
  ["Strategic relevance",14],["Timing",18],["Evidence strength",20],["Service-need clarity",12],
  ["Commercialization complexity",10],["Narrative complexity",8],["RC differentiation",10],["Risk-adjusted priority",8]
];
const sourceClasses={
  "Official public":{acquire:"Direct official retrieval",store:"Public research workspace",model:"Approved bounded tasks",output:"Cited factual record",audience:"Pilot reviewers",retain:"Per documented schedule"},
  "Public copyrighted":{acquire:"Lawful public access",store:"Link + limited excerpt",model:"Terms-aware use only",output:"Citation-led synthesis",audience:"Restricted to purpose",retain:"Minimize copied content"},
  "Licensed commercial":{acquire:"Entitlement required",store:"Approved controlled zone",model:"Contract-specific",output:"No redistribution beyond rights",audience:"Authorized users only",retain:"License controls"},
  "RC proprietary":{acquire:"Internal authority required",store:"Controlled enterprise",model:"Approved RC environment",output:"Internal-calibrated layer",audience:"Named internal roles",retain:"RC policy"},
  "Client confidential":{acquire:"Client + purpose authority",store:"Client-restricted zone",model:"Approved case-specific use",output:"No Pilot 1 use",audience:"Authorized matter team",retain:"Contract + policy"},
  "Sensitive / regulated":{acquire:"Legal basis and necessity",store:"Regulated zone",model:"Special approval",output:"Excluded from Pilot 1",audience:"Strictly limited",retain:"Minimize / mandated"},
  "Derived intelligence":{acquire:"Inherits upstream rights",store:"Same-or-higher control",model:"Traceable transformations",output:"Restriction-preserving",audience:"Per upstream record",retain:"Linked lifecycle"}
};
const weeks=[
  ["Scope","Decision, perimeter, governance, schema","Scope memo + source perimeter","Scope, geography, stage, reader, priorities","Scope approval"],
  ["Taxonomy","Signals, assumptions, evidence rules, entity model","Ontology + assumption register","Therapeutic boundaries","Method approval"],
  ["Universe","Candidate discovery and inclusion/exclusion","50–75-company universe","None beyond approved scope","Universe review"],
  ["Verify","Primary-source checks and entity resolution","Normalized evidence records","Clarification only","Record validation"],
  ["Score","Weights, sensitivity, missing data, false positives","External score + sensitivity memo","Success interpretation","Analytical approval"],
  ["Dossiers","Priority-account evidence packages","Draft source-linked dossiers","Optional expert questions","Account review"],
  ["Portfolio","Advance, monitor, defer, exclude, redirect","12–15 accounts + rejected list","Internal discussion context","Portfolio review"],
  ["Handoff","Evaluation, limits, recommendation, next-stage choice","Final package + recommendation","Decision on whether to calibrate","Distribution approval"]
];
function renderStep(key){const d=evidenceSteps[key];const el=document.querySelector("#stepDetail");el.innerHTML=`<p class="label">${key}</p><h3>${d.title}</h3><p>${d.body}</p><dl>${d.meta.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join("")}</dl>`}
function initStepper(){document.querySelectorAll(".stepper button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".stepper button").forEach(x=>x.setAttribute("aria-selected","false"));b.setAttribute("aria-selected","true");renderStep(b.dataset.step)}));renderStep("source")}
function initScores(){const wrap=document.querySelector("#sliders");weights.forEach(([name,val],i)=>{wrap.insertAdjacentHTML("beforeend",`<label class="slider-row"><span>${name}</span><input type="range" min="0" max="25" value="${val}" data-i="${i}"><output>${val}</output></label>`)});const update=()=>{const vals=[...wrap.querySelectorAll("input")].map(x=>+x.value);const raw=vals.reduce((a,b)=>a+b,0);const score=Math.round(Math.min(100,raw*.74));document.querySelector("#scoreValue").textContent=score;document.querySelector("#scoreRing").style.background=`conic-gradient(var(--teal) 0 ${score}%,var(--fog) ${score}%)`;const disp=score>=72?"ADVANCE TO HUMAN REVIEW":score>=56?"MONITOR / RESOLVE QUESTIONS":"DEFER / INSUFFICIENT EVIDENCE";document.querySelector("#disposition").textContent=disp;const ranked=vals.map((v,i)=>[v,weights[i][0]]).sort((a,b)=>b[0]-a[0]).slice(0,2).map(x=>x[1].toLowerCase());document.querySelector("#scoreReason").textContent=`${ranked[0]} and ${ranked[1]} currently drive the result. The score does not authorize pursuit.`};wrap.querySelectorAll("input").forEach(i=>i.addEventListener("input",e=>{e.target.nextElementSibling.textContent=e.target.value;update()}));update()}
function initSources(){const opts=document.querySelector("#sourceOptions"),path=document.querySelector("#permissionPath");Object.keys(sourceClasses).forEach((name,i)=>opts.insertAdjacentHTML("beforeend",`<button role="tab" aria-selected="${i===0}" data-source="${name}">${name}</button>`));const render=name=>{const s=sourceClasses[name];path.innerHTML=[["Acquire",s.acquire],["Store",s.store],["Model use",s.model],["Output",s.output],["Audience",s.audience],["Retention",s.retain]].map(([a,b],i)=>`<div><span>0${i+1} · ${a}</span><strong>${name}</strong><small>${b}</small></div>`).join("")};opts.addEventListener("click",e=>{if(!e.target.matches("button"))return;opts.querySelectorAll("button").forEach(b=>b.setAttribute("aria-selected","false"));e.target.setAttribute("aria-selected","true");render(e.target.dataset.source)});render(Object.keys(sourceClasses)[0])}
function initWeeks(){const track=document.querySelector("#weekTrack"),detail=document.querySelector("#weekDetail");weeks.forEach((w,i)=>track.insertAdjacentHTML("beforeend",`<button role="tab" aria-selected="${i===0}" data-week="${i}"><span>WEEK ${i+1}</span><strong>${w[0]}</strong></button>`));const render=i=>{const w=weeks[i];detail.innerHTML=[["Activities",w[1]],["Output",w[2]],["Real Chemistry input",w[3]],["Human gate",w[4]]].map(([a,b])=>`<div><span>${a}</span><p>${b}</p></div>`).join("")};track.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;track.querySelectorAll("button").forEach(x=>x.setAttribute("aria-selected","false"));b.setAttribute("aria-selected","true");render(+b.dataset.week)});render(0)}
function initPaths(){const map={approve:["Proposal → Pilot → Decision","#proposal"],method:["Method → Decision room → Timeline","#method"],risk:["Governance → Source rights → Materials","#governance"],fit:["Capability fit → Internal questions → Decision","#fit"]};document.querySelectorAll(".intent").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".intent").forEach(x=>x.classList.remove("active"));b.classList.add("active");const [title,href]=map[b.dataset.path];document.querySelector("#pathTitle").textContent=title;document.querySelector("#pathLink").href=href;document.querySelectorAll("[data-route]").forEach(s=>s.classList.toggle("dimmed",!s.dataset.route.includes(b.dataset.path)));setTimeout(()=>document.querySelectorAll("[data-route]").forEach(s=>s.classList.remove("dimmed")),900)}))}
function initShell(){const nav=document.querySelector("#primaryNav"),toggle=document.querySelector(".menu-toggle");toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",open)});const setProgress=()=>{const h=document.documentElement;const pct=h.scrollTop/(h.scrollHeight-h.clientHeight)*100;document.querySelector("#progressBar").style.width=`${pct}%`};addEventListener("scroll",setProgress,{passive:true});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.hash===`#${e.target.id}`))}}),{rootMargin:"-35% 0px -55%"});document.querySelectorAll("main section[id]").forEach(s=>io.observe(s));const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});document.querySelectorAll(".section>*,.boundary,.download-grid article").forEach(x=>{x.classList.add("reveal");reveal.observe(x)})}
function initExtras(){document.querySelector("#toggleEvidence").addEventListener("click",e=>{const d=document.querySelector("#evidenceDrawer");d.hidden=!d.hidden;e.target.textContent=d.hidden?"Open evidence drawer":"Close evidence drawer"});document.querySelectorAll(".accordion").forEach(b=>b.addEventListener("click",()=>{const open=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",String(!open));b.nextElementSibling.classList.toggle("open",!open)}));const dlg=document.querySelector("#versionDialog");document.querySelector("#openVersion").addEventListener("click",()=>dlg.showModal());dlg.querySelector(".dialog-close").addEventListener("click",()=>dlg.close())}
initStepper();initScores();initSources();initWeeks();initPaths();initShell();initExtras();
